---
\$schema: "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#"
contentVersion: "1.0.0.0"
parameters:
  vmName:
    type: string
    metadata:
      description: "Name of the virtual machine."
  adminUsername:
    type: string
    metadata:
      description: "Admin username for the virtual machine."
  adminPassword:
    type: secureString
    metadata:
      description: "Admin password for the virtual machine."
  vmSize:
    type: string
    defaultValue: "Standard_DS1_v2"
    metadata:
      description: "Size of the virtual machine."
resources:
  - type: "Microsoft.Network/virtualNetworks"
    apiVersion: "2020-06-01"
    name: "myVnet"
    location: "[resourceGroup().location]"
    properties:
      addressSpace:
        addressPrefixes:
          - "10.0.0.0/16"
      subnets:
        - name: "mySubnet"
          properties:
            addressPrefix: "10.0.0.0/24"
  - type: "Microsoft.Network/publicIPAddresses"
    apiVersion: "2020-06-01"
    name: "myPublicIP"
    location: "[resourceGroup().location]"
    properties:
      publicIPAllocationMethod: "Dynamic"
  - type: "Microsoft.Network/networkInterfaces"
    apiVersion: "2020-06-01"
    name: "myNic"
    location: "[resourceGroup().location]"
    properties:
      ipConfigurations:
        - name: "ipconfig1"
          properties:
            subnet:
              id: "[resourceId('Microsoft.Network/virtualNetworks/subnets', 'myVnet', 'mySubnet')]"
            privateIPAllocationMethod: "Dynamic"
            publicIPAddress:
              id: "[resourceId('Microsoft.Network/publicIPAddresses', 'myPublicIP')]"
  - type: "Microsoft.Compute/virtualMachines"
    apiVersion: "2020-06-01"
    name: "[parameters('vmName')]"
    location: "[resourceGroup().location]"
    properties:
      hardwareProfile:
        vmSize: "[parameters('vmSize')]"
      osProfile:
        computerName: "[parameters('vmName')]"
        adminUsername: "[parameters('adminUsername')]"
        adminPassword: "[parameters('adminPassword')]"
      networkProfile:
        networkInterfaces:
          - id: "[resourceId('Microsoft.Network/networkInterfaces', 'myNic')]"
      storageProfile:
        imageReference:
          publisher: "MicrosoftWindowsServer"
          offer: "WindowsServer"
          sku: "2019-Datacenter"
          version: "latest"